# /// script
# requires-python = ">=3.10"
# dependencies = ["protego==0.7.0"]
# ///
"""Build the shared benchmark input, deterministically (same bytes on every platform):

- bench/robots.txt: a large, realistic file (~100 KB): a global group and 40 crawler
  groups, rules with wildcards and `$`, comments, sitemaps.
- bench/paths.txt: 10 crawlers x 1,000 paths, one `user_agent path` per line, grouped
  by crawler. 2 of the 10 crawlers have no group, so `*` applies to them.

The input stays inside what every implementation agrees on (ASCII only, no percent
escapes, plain product tokens, no BOM, no lines between user-agent lines), so the
checksum is the same for the Rust reference and every port. Prints the checksum:
the sum of (line number) over the lines whose path is allowed.

Run from the repo root:  uv run bench/generate.py
"""

import hashlib
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("gen", ROOT.parent / "conformance" / "generate" / "generate.py")


def rand(seed: str, n: int) -> int:
    """Deterministic integer in [0, n): SHA-256, stable across Python versions."""
    return int.from_bytes(hashlib.sha256(seed.encode()).digest()[:8], "big") % n


WORDS = ["admin", "api", "assets", "blog", "cart", "checkout", "docs", "download", "en", "fr", "help",
         "images", "img", "js", "login", "media", "news", "p", "private", "products", "search", "shop",
         "static", "tag", "tmp", "user", "v1", "v2", "wiki", "wp-admin"]
EXTS = ["html", "php", "pdf", "json", "xml", "jpg", "png", "js", "css", "txt"]
BOTS = [f"Crawler{chr(65 + i // 26)}{chr(65 + i % 26)}{chr(97 + (i * 7) % 26)}bot" for i in range(40)]  # product tokens: letters only


def word(seed: str) -> str:
    return WORDS[rand(seed, len(WORDS))]


def pattern(seed: str) -> str:
    depth = 1 + rand(seed + "d", 3)
    p = "/" + "/".join(word(f"{seed}/{k}") for k in range(depth))
    kind = rand(seed + "k", 10)
    if kind == 0:
        p += "/*." + EXTS[rand(seed + "e", len(EXTS))] + "$"
    elif kind == 1:
        p += "*?" + word(seed + "q") + "="
    elif kind == 2:
        p = "/*/" + word(seed + "w") + "/"
    elif kind <= 4:
        p += "/"
    return p


def group(name: str, n: int) -> list[str]:
    lines = [f"User-agent: {name}"]
    for r in range(n):
        allow = rand(f"{name}:{r}:a", 4) == 0
        lines.append(f"{'Allow' if allow else 'Disallow'}: {pattern(f'{name}:{r}')}")
        if rand(f"{name}:{r}:c", 15) == 0:
            lines.append("# " + word(f"{name}:{r}:c1") + " section")
    return lines


def robots() -> str:
    out = ["# Benchmark input for the robots.txt spec. Generated by bench/generate.py.", ""]
    out += group("*", 400) + [""]
    for i, bot in enumerate(BOTS):
        out += group(bot, 30 + rand(bot, 90)) + [""]
        if i % 10 == 9:
            out.append(f"Sitemap: https://www.example.com/sitemap-{i // 10}.xml")
            out.append("")
    return "\n".join(out) + "\n"


def path(seed: str) -> str:
    depth = 1 + rand(seed + "d", 4)
    p = "/" + "/".join(word(f"{seed}/{k}") for k in range(depth))
    if rand(seed + "f", 2):
        p += "/" + word(seed + "f1") + str(rand(seed + "n", 100)) + "." + EXTS[rand(seed + "e", len(EXTS))]
    if rand(seed + "q", 4) == 0:
        p += "?" + word(seed + "q1") + "=" + str(rand(seed + "v", 1000))
    return p


def paths() -> list[tuple[str, str]]:
    agents = [BOTS[3], BOTS[11], BOTS[17], BOTS[24], BOTS[29], BOTS[33], BOTS[38], BOTS[5], "OtherBot", "UnlistedBot"]
    return [(a, path(f"{a}:{i}")) for a in agents for i in range(1000)]


def main() -> None:
    text = robots()
    pairs = paths()
    (ROOT / "robots.txt").write_text(text)
    (ROOT / "paths.txt").write_text("".join(f"{a} {p}\n" for a, p in pairs))
    gen = importlib.util.module_from_spec(spec)
    sys.modules["gen"] = gen  # dataclasses with postponed annotations look their module up
    spec.loader.exec_module(gen)
    parsed = gen.spec_parse(text.encode())
    allowed = [gen.spec_is_allowed(parsed, a, p) for a, p in pairs]
    checksum = sum(i + 1 for i, ok in enumerate(allowed) if ok)
    # The oracle must agree on every lookup, or the input strays into a recorded difference.
    oracle = gen.Protego.parse(text)
    differ = [i for i, (a, p) in enumerate(pairs) if oracle.can_fetch("https://www.example.com" + p, a) != allowed[i]]
    assert not differ, f"protego disagrees on {len(differ)} lookups, e.g. line {differ[0] + 1}: {pairs[differ[0]]}"
    print(f"bench/robots.txt: {len(text.encode()):,} bytes, {len(parsed.groups)} groups, "
          f"{sum(len(g.rules) for g in parsed.groups):,} rules; bench/paths.txt: {len(pairs):,} lookups, "
          f"{sum(allowed):,} allowed; checksum {checksum}")


if __name__ == "__main__":
    sys.exit(main())
